#!/usr/bin/env ruby

require "json"
require "httpclient"

filename = ARGV[0] or raise "must provide a filename"
slug = ARGV[1] || "tddforandroid"
api_key = ENV["LEANPUB_API_KEY"] or raise "missing env var LEANPUB_API_KEY"

content = File.read(filename)
headers = { "Content-Type" => "text/plain"}

url = "https://leanpub.com/#{slug}/preview/single.json?api_key=#{api_key}"
response = HTTPClient.new.post(url, :body => content, :header => headers)
puts response.status
puts response.content


while true
  url = "https://leanpub.com/#{slug}/book_status?api_key=#{api_key}"
  response = HTTPClient.new.get(url)
  puts response.status
  response = JSON.parse(response.content)
  puts "Status: " + response["status"]
  puts "Message: " + response["message"]
end