#!/bin/bash

set -e
cd "$(dirname "$0")"/..

[ $# = 1 ] || {
  echo "Usage: $0 <commit message>"
  exit 1
}

[ -z "$LEANPUB_API_KEY" ] && {
  echo "Please setup your LEANPUB_API_KEY env var"
  exit 1
}

commit_message="$1"

ls *-*.md > Book.txt
ls "200-unit-doctor.md" > Sample.txt

for project in UnitDoctor UnitConversionSpike FairyFingers; do
  mkdir -p code/$project 2> /dev/null
  find ../our-android-examples/$project -name \*.java -o -name \*.xml -exec cp {} code/$project \;
done
git add -A :/
git commit -m "$commit_message" || true
git pull -r
git push

# generate preview
curl -d "api_key=$LEANPUB_API_KEY" https://leanpub.com/tddforandroid/preview.json
sleep 3
script/status
script/download-preview
