#!/bin/bash

set -e
cd "$(dirname "$0")"/..

[ $# = 1 ] || {
  echo "Usage: $0 <commit message>"
  exit 1
}

[ -z "$LEANPUB_API_KEY" ] && {
  echo "Please setup your LEANPUB_API_KEY env var"
  exit 1
}

commit_message="$1"

ls *-*.md > Book.txt

for project in UnitDoctor FairyFingers; do
  rsync -a ../our-android-examples/$project code
done
git add -A :/
git commit -m "$commit_message"
git pull -r
git push

# generate preview
curl -d "api_key=$LEANPUB_API_KEY" https://leanpub.com/tddforandroid/preview.json
sleep 3
script/status
script/download-preview
