#!/bin/bash

set -e
cd "$(dirname "$0")"/..

[ $# = 1 ] || {
  echo "Usage: $0 <commit message>"
  exit 1
}

commit_message="$1"

ls -1 *-*.md > Book.txt

git add -A .
git commit -m "$commit_message"
git push
sleep 3
script/status