#!/bin/bash

set -e

[ -z "$LEANPUB_API_KEY" ] && {
  echo "Please setup your LEANPUB_API_KEY env var"
  exit 1
}

slug="tddforandroid"
status=""
while ! echo $status | grep -q "Book generation complete"
do
  response=$(curl -s "https://leanpub.com/$slug/book_status?api_key=$LEANPUB_API_KEY")
  status=$(echo $response | tr , '\n' | grep -e message -e status)
  echo $status
  sleep 3
done
echo "done"
